### ISSUE TITLE
Slider?

### ISSUE THREAD

**Issue by monoplex** [AKAspanion/ui-neumorphism#10]
Very beautiful and for Web too - ideal. But have I missed it, no Slider?

   Thanks.

**Comment by AKAspanion** [comment]
@monoplex 
Maybe these?
https://akaspanion.github.io/ui-neumorphism/carousel
https://akaspanion.github.io/ui-neumorphism/tabs

**Comment by monoplex** [comment]
Many thanks for your speedy reply and suggestions. Not quite what I am looking for though. I'm an engineer building a little web app with some front panel-like controls working on the end of a websocket from an astonishing tiny IOT device - ESP32.

Like your stuff and thanks again.
