### ISSUE TITLE
Unable to change button font size.

### ISSUE THREAD

**Issue by pietdaniel** [AKAspanion/ui-neumorphism#30]
I cannot change the font-size of the button. I would expect the following to work:

```javascript
<Button style={{fontSize: '5px'}} />
```

I believe [this value](https://github.com/AKAspanion/ui-neumorphism/blob/1c27e9cb0fd0063c2fb9f12cd68ccfc646c74dae/src/components/button/Button.module.css#L181) is the culprit.

**Comment by AKAspanion** [comment]
@pietdaniel 
You can try this.
.nu-button-inner {
    font-size: 16px !important;
}

**Comment by pietdaniel** [comment]
What about something like this: https://github.com/AKAspanion/ui-neumorphism/compare/master...pietdaniel:ui-neumorphism:master

The reasoning behind this is to have a `xs` variant and to have the `sm` variant be smaller. Something like:
 
<img width="193" alt="Screen Shot 2023-07-15 at 9 28 36 PM" src="https://github.com/AKAspanion/ui-neumorphism/assets/1924983/eee54a3c-c0c3-471d-a8c4-5ac23d38d240">
