### ISSUE TITLE
Failed Prop type  NuTabs

### ISSUE THREAD

**Issue by intersector** [AKAspanion/ui-neumorphism#5]
Hello, whatever i tried constantly these errors pop in console:
Warning: Failed prop type: NuTabs: prop type `style` is invalid; it must be a function, usually from the `prop-types` package, but received `object`.
Warning: Failed prop type: NuTabs: prop type `className` is invalid; it must be a function, usually from the `prop-types` package, but received `string`.

Thanks and great work by the way

**Comment by AKAspanion** [comment]
@intersector HI, Can u send the console error screenshot of the same? Thanks.

**Comment by intersector** [comment]
![image](https://user-images.githubusercontent.com/12218883/98794733-0e213280-2412-11eb-8749-b77fb13fa681.png)
Hi thanks for reply, take a look

**Comment by AKAspanion** [comment]
@intersector issue is now resolved, please update to the new version.
