### ISSUE TITLE
TextField bug

### ISSUE THREAD

**Issue by pravosleva** [AKAspanion/ui-neumorphism#7]
[Look](https://github.com/AKAspanion/ui-neumorphism/blob/master/src/components/input/TextField.jsx#L34)

`TextFileld` will not refresh if `props.value` will be updated. Need to fix this!

**Comment by AKAspanion** [comment]
@pravosleva 
[here](https://github.com/AKAspanion/ui-neumorphism/blob/master/src/components/input/TextField.jsx#L117)
I have added a boolean prop `uncontrolled` that changes the behavior of TextField to uncontrolled component.
Hopefully, this solves the issue.

**Comment by pravosleva** [comment]
@AKAspanion 
Ok, thanks.

But coud you please add type for `uncontrolled` field (line 499 on screenshot)
![изображение](https://user-images.githubusercontent.com/19761493/107689173-92a57a80-6cb9-11eb-9fe2-72a68813fe08.png)
