### ISSUE TITLE
No Type definition with "overrideThemeVariables"

### ISSUE THREAD

**Issue by seito2** [AKAspanion/ui-neumorphism#8]
Hi, 

I try to use overrideThemeVariables in typescript, but it doesn't decleared.

![スクリーンショット 2021-02-17 9 31 51](https://user-images.githubusercontent.com/42537610/108139285-1cfb3d80-7103-11eb-9467-a9dca42773dc.png)

So I think we should add type definition in index.d.ts

If it is okay to submit a pull request, I will do so!

Thanks!

**Comment by AKAspanion** [comment]
@seito2 Please, feel free to submit a pull request.
