### ISSUE TITLE
Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `NuSwitch`, expected `string`.

### ISSUE THREAD

**Issue by Guuri11** [AKAspanion/ui-neumorphism#9]
I want to use an Icon as Switch Label, but it only accepts Strings... It accepts it but it's bit annoying seeing every time this warning while debugging, so I would like to know if it is possible to change property type??

Salutes!!

**Comment by AKAspanion** [comment]
@Guuri11  One way you can solve this is by putting the icon next to the switch, instead of passing it to the label prop?

**Comment by Guuri11** [comment]
Yeah, that's a way to solve, anyway I've used a button with state instead of switch. 

Thanks!
